- integration/justmock-console.md
Updates to the command lines and new example for .net core
> Updates to the command lines

- getting-started/installation-instructions.md
Update to the net core support message to reflect that later version of .Net Core after 2.0 are also supported
> Update to the net core support message

- web.config
Necessary for the new top navigation in order to work the shopping cart and account.
> fix: Added https redirect

- basic-usage/mock-behaviors/recursiveloose.md
> RecursiveLoose behavior requires better documentation

- basic-usage/asserting-occurrence.md
o added AfterAll description and example
> Extend public API with call prerequisites verification

- advanced-usage/mocking-non-public-members-and-types.md
o extended non-public class mocking article
> Mocking of non-public classes

- advanced-usage/mocking-non-public-members-and-types.md
- advanced-usage/private-accessor.md
o extended non-public article with instance/static generic mocking
o fixed sample code formatting
> Mock Generics with NonPublic API

- advanced-usage/future-mocking.md
The C# language specifier was missing for some of the code snippets
> Adding missing C# language specifier

- advanced-usage/future-mocking.md
- advanced-usage/mocking-non-public-members-and-types.md
- advanced-usage/private-accessor.md
Merge the documentation for the new features from R3 2019 release to master branch
> Merge R3.2019 new features documentation

- basic-usage/automocking.md
o modified documentation examples
> Implement ArrangeSet and AssertSet methods for MockingContainer

- advanced-usage/mocking-non-public-members-and-types.md
- advanced-usage/ref-return-mocking.md
- cheat-sheet.md
o updated documentation articles
> Provide API improvements for argument matchers

- getting-started/installation-instructions.md
- introduction.md
Implementing best practices for introduction pages
> Implementing best practices

- advanced-usage/profiler-log-and-trace.md
> Profiler log and trace

- getting-started/system-requirements.md
Update the system requirements with the latest information
> Update the system requirements

- getting-started/using-telerik-justmock-in-your-test-project.md
Add the information from where the required Dll for .NET Core and .NET 5 should be referenced
> Add info about the latest .NET version

- basic-usage/create-mocks-by-example.md
- The content is refactored and reordered
- The title is changed to avoid confusion
> Refactoring Create Mocks by Example topic

- basic-usage/recursive-mocking.md
The title of the topic inside the navigation tree is changed as well
> [Recursive Mocking] Improved styling and information

- basic-usage/mock-properties.md
- Mostly styling updates and rewording
- A list of snippets is unified into a single one for better readability
> Updated Mock Properties

- getting-started/video-onboarding.md
This PR adds an article dedicated to the new JustMock course and aims at promoting the new training materials.
> Add Video Onboarding Article

- .github/workflows/publish-kb.yml
- _config.yml
- knowledge-base/mock-limitations.md
- Added knowledge base section.
- Add mocking limitation article.
- Added workflow for publishing KB articles for support heroes portal.
> Knowledge base

- _assetsApi/docfx-tmpl/src/partials/footer.tmpl.partial
- _config.yml
Integrated new feedback form in docs and api ref. Replaced sheetId with productCode.
> Replace sheetId with productCode

- web.config
> Updated redirect rule for licensing
